Repository Hold-Krykke/3SemProject_BackEnd, pull requests merged in 2019-12, with the labels that each got.

#24 Test Driven Development of 5 days Weather forecast endpoint
  src/main/java/facades/WeatherFacade.java
  src/main/java/rest/WeatherResource.java
  src/test/java/facades/WeatherFacadeTest.java
  src/test/java/rest/WeatherResourceTest.java
Labels: SPRINT 2

#25 Added more error messages to Swagger
  src/main/java/facades/CountryFacade.java
  src/main/java/rest/CountryResource.java
  src/main/java/utils/APIUtil.java
  src/test/java/rest/CountryResourceTest.java
Labels: SPRINT 3

#26 Added a guard that throws exception if there are no events at all
  src/main/java/facades/EventFacade.java
  src/main/java/rest/CountryResource.java
Labels: SPRINT 3, bug

#27 Update README.md
  README.md
Labels: SPRINT 3

#28 UTF-8 bugfix
  src/main/java/facades/EventFacade.java
  src/main/java/utils/APIUtil.java
Labels: SPRINT 3, bug

#29 change test to reflect eventfacade changes
  src/test/java/rest/CountryResourceTest.java
Labels: SPRINT 3
