Repository Hold-Krykke/3SemProject_BackEnd, pull requests merged in 2019-11, with the labels that each got.

#7 Initial codebase
  .gitignore
  .travis.yml
  pom.xml
  src/main/java/cors/CorsRequestFilter.java
  src/main/java/cors/CorsResponseFilter.java
  src/main/java/dto/DTOExample.java
  src/main/java/errorhandling/ExceptionDTO.java
  src/main/java/errorhandling/GenericExceptionMapper.java
  src/main/java/errorhandling/NotFoundException.java
  src/main/java/facades/FacadeExample.java
  src/main/java/rest/ApplicationConfig.java
  src/main/java/rest/RenameMeResource.java
  src/main/webapp/META-INF/context.xml
  src/main/webapp/index.html
  src/test/java/facades/FacadeExampleTest.java
  src/test/java/rest/RenameMeResourceTest.java
Labels: SPRINT 1

#10 5cities endpoint
  pom.xml
  src/main/java/dto/CountryDTO.java
  src/main/java/errorhandling/GenericExceptionMapper.java
  src/main/java/facades/CountryFacade.java
  src/main/java/facades/FacadeExample.java
  src/main/java/rest/ApplicationConfig.java
  src/main/java/rest/CountryResource.java
  src/test/java/facades/CountryFacadeTest.java
  src/test/java/facades/FacadeExampleTest.java
  src/test/java/rest/CountryResourceTest.java
Labels: SPRINT 1

#12 Created getCountryNameByAlpha2 endpoint
  src/main/java/dto/CountryDTO.java
  src/main/java/facades/CountryFacade.java
  src/main/java/rest/CountryResource.java
Labels: SPRINT 1

#14 Improved error handling
  src/main/java/facades/CountryFacade.java
Labels: SPRINT 1

#13 Testing
  src/test/java/facades/CountryFacadeTest.java
  src/test/java/rest/CountryResourceTest.java
Labels: SPRINT 1

#11 US1 - facade, countries w/ 5 biggest cities
  src/main/java/dto/CityDTO.java
  src/main/java/dto/CountryDTO.java
  src/main/java/dto/DTOExample.java
  src/main/java/facades/CountryFacade.java
  src/main/java/utils/APIUtil.java
  src/test/java/facades/CountryFacadeTest.java
  src/test/java/rest/CountryResourceTest.java
  src/test/java/utils/APIUtilTest.java
Labels: DON'T MERGE, SPRINT 1

#16 Shortened REST tests
  src/test/java/rest/CountryResourceTest.java
Labels: SPRINT 1

#15 US1 - 5 biggest cities in countries Pt. 2
  src/main/java/dto/CountryDTO.java
  src/main/java/errorhandling/APIUtilException.java
  src/main/java/facades/CountryFacade.java
  src/main/java/rest/CountryResource.java
  src/main/java/utils/APIUtil.java
  src/test/java/facades/CountryFacadeTest.java
  src/test/java/rest/CountryResourceTest.java
Labels: SPRINT 1

#9 User Story 1 - Endpoint that can return data from ticketmaster api
  pom.xml
  src/main/java/dto/EventDTO.java
  src/main/java/dto/LocationDateDTO.java
  src/main/java/facades/CountryFacade.java
  src/main/java/facades/EventFacade.java
  src/main/java/rest/CountryResource.java
  src/test/java/facades/EventFacadeTest.java
  src/test/java/rest/CountryResourceTest.java
Labels: SPRINT 1

#20 Bugfix: Test failure @ too many API calls
  src/test/java/rest/CountryResourceTest.java
Labels: SPRINT 1

#21 Bugfix: Errorhandling for 'getSpecificCityByName'
  src/main/java/dto/CountryDTO.java
Labels: SPRINT 1

#23 Weather API
  src/main/java/dto/WeatherDTO.java
  src/main/java/facades/WeatherFacade.java
  src/main/java/rest/ApplicationConfig.java
  src/main/java/rest/WeatherResource.java
  src/test/java/facades/WeatherFacadeTest.java
  src/test/java/rest/WeatherResourceTest.java
Labels: SPRINT 2
